### ISSUE TITLE
Class IDs

### ISSUE THREAD

**Issue by hannogrimm** [apugh/realm-api-docs#11]
Hey @apugh, could you provide a list of the class names with their IDs?

**Comment by apugh** [comment]
2285	MaleTank
2493	FemaleDamage
2494	FemaleSupport
2495	MaleUtility
2496	MaleFlank

I don't yet know how these 5 names map to Warrior, Mage, Hunter, Engineer, Assassin.

**Comment by apugh** [comment]
2285	MaleTank (Warrior)
2493	FemaleDamage (Hunter)
2494	FemaleSupport (Mage)
2495	MaleUtility (Engineer)
2496	MaleFlank (Assassin)
