### ISSUE TITLE
Weird structure for getPlayerStats

### ISSUE THREAD

**Issue by hannogrimm** [apugh/realm-api-docs#12]
The current structure of getPlayerStats is confusing right now. How are the stats split up? For each queue the aggregated statistics + a breakdown of each class performance in that queue

OR

For each class the aggregated statistics + a breakdown for this class in each queue?

It seems like #2 is the current way its handled. Doesn't it make more sense to break it down by queue->classes instead of class->queues to allow an optional queue parameter in the future (to eliminate the need for a getQueueStats)?

**Comment by apugh** [comment]
If you are familiar with DB architecture the primary key for the player's overall stats table is the 3 values:  player_id, match_queue_id, class_id.

With 5 classes and 3 queues this would mean a grand total of 15 "detailed" breakdowns.

I thought about whether to sub-aggregate at match_queue, and then list the classes beneath it.  Or vice-versa.  But ultimately settled on providing the the aggregated stats plus the 15 (potentially) breakdowns mentioned above, leaving any intermediate aggregation (at either queue or class only) up to the developer.

Still up for debate, but that's how it is now ... :-)

**Comment by hannogrimm** [comment]
I was confused at the beginning, but I got the hang of it now. =)

Sorry for the constant Pull Requests btw, I just guess that the changes proposed are helpful for the whole community. =)
