### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by minemidnight** [apugh/realm-api-docs#20]
Dates should not be in a format as such: `3/18/2018 5:14:27 PM`, but rather a timestamp such as `1521407667000`

**Comment by biromain** [comment]
Date should be in ISO 8601

**Comment by minemidnight** [comment]
Scratch what I said about a timestamp. I like the idea of using ISO 8601 bette

**Comment by apugh** [comment]
I'm OK with introducing this ISO 8601 standard into the Realm API.
