### ISSUE TITLE
Expected time of release

### ISSUE THREAD

**Issue by realmfan** [apugh/realm-api-docs#22]
Hi @apugh ,
First of all, thank you so much for sharing this proposal ! It helps a lot in getting the idea of how api will look like.

May I know when is the expected time of release of realm api ?

The realmtracker website mentions that they will launch on June 27th. So, is that the day when the realm api will be made public too?

Thanks again!

**Comment by apugh** [comment]
There is no firm commitment because so there are so many variables here at Hi-Rez.   But that is my goal at the moment.

**Comment by realmfan** [comment]
Great, thanks for the update!
